# AWS CloudFormation Template - Basic Three-Tier Architecture
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Basic three-tier web application infrastructure'

Parameters:
  ProjectName:
    Type: String
    Default: "my-web-app"
  
Resources:
  # S3 Bucket for Static Website Hosting
  WebAppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-static-website"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  # Lambda Function for Backend Processing
  ProcessFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-processor"
      Runtime: python3.9
      Handler: index.lambda_handler
      Code:
        ZipFile: |
          import json
          def lambda_handler(event, context):
              return {
                  'statusCode': 200,
                  'body': json.dumps('Hello from Lambda!')
              }
      Role: !GetAtt LambdaExecutionRole.Arn

  # IAM Role for Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

Outputs:
  WebsiteURL:
    Description: "URL for website hosted on S3"
    Value: !GetAtt WebAppBucket.WebsiteURL
  BucketName:
    Description: "S3 Bucket Name"
    Value: !Ref WebAppBucket
